### ISSUE TITLE
Alteração logotipo

### ISSUE THREAD

**Issue by washingtoncaetano** [filipebezerra/crsapp#1]
Realizar a troca da logotipo do aplicativo trocando para a nova logo da empresa que é CRJ,
mudar o nome do aplicativo para CRJ.
No site da empresa tem a logomarca http://crjesquadrias.com.br/

**Comment by filipebezerra** [comment]
[Logo em diversos formatos](https://github.com/filipebezerra/crsapp/files/2164761/CRJ.zip)

**Comment by filipebezerra** [comment]
Deve ser usado a logo azul, a mesma do site http://crjesquadrias.com.br/
